title: Mark of Serafina 
author: anaissnow
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am using the GitHub repo to aid me in my journey of coding. And these are one of the many steps.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
